package ${packageName}.ui.main
 
import android.os.Bundle
import ${srcDir}.R
import androidx.appcompat.widget.Toolbar
import org.koin.android.ext.android.inject
import org.koin.core.parameter.parametersOf

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
public class ${activityName} : BaseActivity(), ${contractName}.View {
 
    override val layoutId: Int = R.layout.${mainActivityLayoutName}
    override val toolbarView: Toolbar
        get() = toolbar

    private val mPresenter: ${presenterName} by inject(parameterOf(this))
    
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        loadViews()
    }

    fun loadViews(){
    
    }
    
}