package ${packageName};
 
import android.os.Bundle;
import androidx.appcompat.widget.Toolbar
import ${packageName}.ui.base.BaseActivity
import org.koin.android.ext.android.inject

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
public class ${activityName} extends BaseActivity, ${contractName}.View {
 
    override val layoutId: Int = R.layout.${activityLayoutName}
    override val toolbarView: Toolbar
        get() = toolbar

    private val mPresenter: ${presenterName} by inject(parameterOf(this))
    
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        loadViews()
    }

    fun loadViews(){
    
    }
    
}