package ${packageName};
 
import android.os.Bundle;
import javax.inject.Inject;

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

public class ${activityName} extends BaseActivity, ${contractName}.View {
 
    override val layoutId: Int = R.layout.${activityLayoutName}
    override val toolbarView: Toolbar
        get() = toolbar

    private val mPresenter: ${presenterName} by inject(parameterOf(this))
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        loadViews()
    }

    fun loadViews(){
    
    }
    
}