package ${packageName};
 
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */
  
class ${modelName} : ViewModel(){
    
    

}