package ${packageName};
  
/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */ 
interface ${contractName}{
    
    interface View : BaseContract.View {
 
    }

    interface Presenter : BaseContract.Presenter {
 
    }    
}