package ${packageName};
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */
  
interface ${contractName}{
    
    interface View : BaseContract.View {
 
    }

    interface Presenter : BaseContract.Presenter {
 
    }    
}