package ${packageName};

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
class ${fragmentName} : BaseFragment(), ${contractName}.View {

    companion object {
        fun newInstance() = ${fragmentName}
    }

    private lateinit var viewModel: SecondMedicalOpinionListViewModel
    private val mPresenter: ${presenterName} by inject(parameterOf(this))

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.${fragmentLayoutName}, container, false)
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        viewModel = ViewModelProviders.of(this).get(${modelName}::class.java)
        // TODO: Use the ViewModel
    }
}