package ${packageName};

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */
class ${fragmentName} : BaseFragment() {

    companion object {
        fun newInstance() = ${fragmentName}
    }

    private lateinit var viewModel: SecondMedicalOpinionListViewModel
    private val mPresenter: ${presenterName} by inject(parameterOf(this))

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.${fragmentLayoutName}, container, false)
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        viewModel = ViewModelProviders.of(this).get(${modelName}::class.java)
        // TODO: Use the ViewModel
    }
}