package ${packageName};
 
import android.content.Context;
import javax.inject.Inject;

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */
  
class ${modelName} : ViewModel(){
    
    

}