package ${packageName};

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
class  ${presenterName}: ${contractName}.Presenter (
    private val mView: ${contractName}.View
) : BasePresenter {

    init {
        
    }

}