package ${packageName};

/**
 *
 *  Developed by SergioCT
 *
 *  www.SergioCrespoToubes.com
 *  https://github.com/Sergioct
 *
 *  Code autogenerated. 
 *
 */

class  ${presenterName}(
    private val mView: ${contractName}.View
) : BasePresenter {

    init {
        
    }

}