package ${packageName}.ui.base

import android.app.Application
import androidx.appcompat.app.AppCompatDelegate
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

abstract class BaseFragment : Fragment(), BaseContract.View {

    override fun finishActivity() {
        activity?.finish()
    }

    override fun onResume() {
        super.onResume()
        //AnalyticsTrackers.getTracker()?.setScreenName(javaClass.simpleName)
        //AnalyticsTrackers.getTracker()?.send(HitBuilders.ScreenViewBuilder().build())
    }
}