package ${packageName}.ui.base

import androidx.fragment.app.Fragment

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
abstract class BaseFragment : Fragment(), BaseContract.View {

    override fun finishActivity() {
        activity?.finish()
    }

    override fun onResume() {
        super.onResume()
        //AnalyticsTrackers.getTracker()?.setScreenName(javaClass.simpleName)
        //AnalyticsTrackers.getTracker()?.send(HitBuilders.ScreenViewBuilder().build())
    }
}