package ${packageName}.ui.base

import android.app.Application
import androidx.appcompat.app.AppCompatDelegate
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

interface BaseContract {

    interface View {
        fun finishActivity()
    }

    interface Presenter {
    
    }
}