package ${packageName}.ui.base

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
abstract class BaseActivity : AppCompatActivity(), BaseContract.View {

    abstract val layoutId: Int

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContentView(layoutId)
    }


    override fun onResume() {
        super.onResume()
        //AnalyticsTrackers.getTracker()?.setScreenName(javaClass.simpleName)
        //AnalyticsTrackers.getTracker()?.send(HitBuilders.ScreenViewBuilder().build())
    }

    override fun finishActivity() {
        finish()
    }
}
