package ${packageName}.ui.base

import android.os.Bundle

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
abstract class BasePresenter : BaseContract.Presenter {

    init {

    }

}
