package ${packageName}.ui.base

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
interface BaseContract {

    interface View {
        fun finishActivity()
    }

    interface Presenter {
    
    }
}