package ${packageName}.ui.base

import androidx.annotation.LayoutRes
import com.saludonnet.pacientes.controllers.components.DefaultDrawerView
import com.saludonnet.pacientes.controllers.components.DrawerView

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

abstract class NavigationActivity : BaseActivity() {

    lateinit var mDrawerView: DrawerView

    override fun setContentView(@LayoutRes layoutResID: Int) {
        super.setContentView(layoutResID)
        mDrawerView = DefaultDrawerView(this)
    }

    override fun onStart() {
        super.onStart()
        mDrawerView = DefaultDrawerView(this)
    }

    fun closeDrawer() {
        mDrawerView.closeDrawer()
    }
}