package ${packageName}.di

import org.koin.dsl.module

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
val managerModule = module {
	//factory<EventManager> { DefaultEventManager(androidContext()) }
}