package ${packageName}.di.presenters

import org.koin.dsl.module

/**
 * Developed by Sergio Crespo Toubes
 *
 *		SergioCrespoToubes@gmail.com
 *		https://www.SergioCrespoToubes.com
 *		https://www.github.com/Sergioct
 *
 * 		Code autogenerated
 */
val splashModule = module {
	/*factory { (view: SplashView) ->
		SplashPresenter(view)
	}*/
}