package ${packageName};
  
/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public class ${appName}Application extends Application {

    public static AppComponent appComponent;

    private ApiControllerRetrofit apiControllerRetrofit;
    private Picasso picasso;
    //public static MyRoomDatabase db;

    public static ${appName}Application get(Activity activity){
        return (${appName}Application)activity.getApplication();
    }

    override fun onCreate() {
        super.onCreate()

        AppEventsLogger.activateApp(this)

        initKoin()
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
    }

    private fun initKoin() {
        startKoin {
            androidLogger()
            androidContext(this@SonApplication)
            // androidFileProperties()
            modules(
                listOf(
                    appModule,
                    managerModule
                )
            )
        }
    }

}