package ${packageName};

import android.app.Application
import androidx.appcompat.app.AppCompatDelegate
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin

/**
 *
 *	Developed by SergioCT
 *
 *	www.SergioCrespoToubes.com
 *	https://github.com/Sergioct
 *
 * 	Code autogenerated. 
 *
 */

public class ${appName}Application : Application() {

    override fun onCreate() {
        super.onCreate()

        initKoin()
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
    }

    private fun initKoin() {
        startKoin {
            androidLogger()
            androidContext(this@SonApplication)
            // androidFileProperties()
            modules(
                listOf(
                    appModule,
                    managerModule,
                    splashModule,
                    mainModule
                )
            )
        }
    }

}